# configuration
DEBUG = True
SECRET_KEY = 'development key'
SQLALCHEMY_DATABASE_URI = 'sqlite:////tmp/flaskr.db'
RECAPTCHA_PUBLIC_KEY="6Le9acwSAAAAAD-7ASmsSu0ibGqR-Ea0xKK8zr4-"
RECAPTCHA_PRIVATE_KEY="6Le9acwSAAAAACiu3HAoOfTC9KXMPl_aBmY23glP"
